services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: warehouse
      MYSQL_USER: warehouse_user
      MYSQL_PASSWORD: warehouse_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://warehouse_user:warehouse_pass@db:3306/warehouse?serverVersion=8.0&charset=utf8mb4"
      APP_ENV: dev
      APP_SECRET: "dev-secret-key-change-in-production"
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  db_data: